version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing dependecies...
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - touch .env
      - echo REACT_APP_OPT_META_HOST=\"$REACT_APP_OPT_META_HOST\" >> .env
      - echo REACT_APP_TERMINOLOGY_HOST=\"$REACT_APP_TERMINOLOGY_HOST\" >> .env
      - cat .env
      - npm run-script build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp build s3://$BUCKET_NAME/ --recursive --acl public-read