export default {
    FREE_TEXT:"FREE_TEXT",
    INTERNAL_CODED_TEXT: "INTERNAL_CODED_TEXT",
    EXTERNAL_CODED_TEXT: "EXTERNAL_CODED_TEXT",
    CONSTRAINED_TEXT: "CONSTRAINED_TEXT",
    QUANTITY: "QUANTITY",
    COUNT: "COUNT",
    DATE: "DATE",
    DATETIME: "DATETIME",
    ORDINAL: "ORDINAL",
    BOOLEAN_CHECK: "BOOLEAN_CHECK",
    DURATION: "DURATION"
}